version: '3'
services:
  bing-server:
    build:
      context: .
    restart: unless-stopped
    volumes:
      - .:/bing:cached
    ports:
      - 443:443

  web:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./static:/usr/share/nginx/html
    ports:
      - 443:443
